import styles from "../styles/Home.module.scss";
import { useState, useEffect } from "react";
import { func } from "prop-types";

export default function Home() {
	const [timerCountValue, setTimerCountValue] = useState(0);

	useEffect(() => {
		setInterval(() => {
			changeProgress();
		}, 100);
		return () => clearInterval();
	}, []);

	function changeProgress() {
		setTimerCountValue((prev) => {
			if (prev <= -730) {
				return 0;
			}
			return Number(prev) - 1;
		});
	}

	return (
		<div className={styles.wrapper}>
			<header>
				<title>Quiz</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://use.typekit.net/sly1ocm.css"
				/>
				<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
			</header>

			<main className={styles.main}>
				<div className={styles.quizContainer}>
					<div
						style={{
							boxShadow: `inset ${timerCountValue}px 0 0 0 #fefefe`
						}}
						className={styles.quizTimeLine}></div>
					<div className={styles.quizTitle}>
						WHICH IS THE MISSING LINE?
					</div>
					<div className={styles.quizQuestionContainer}>
						<pre class="prettyprint">
							function hello() &#123; const item =
							document.querySelector(".item");&#125;
						</pre>
					</div>

					<div className={styles.quizAnswers}>
						<div className={styles.answer}>
							<div>
								<span>A</span>
							</div>
							<pre class="prettyprint linenums">
								const item =document.querySelector(".item");
							</pre>
						</div>
						<div className={styles.answer}>
							<div>
								<span>B</span>
							</div>
							<pre class="prettyprint linenums">
								const item =document.querySelector(".item");
							</pre>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
