import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/sly1ocm.css" />
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

      </Head>

      <main className={styles.main}>
        <div className={styles.quizContainer}>
          <div className={styles.quizTimeLine}></div>
          <div className={styles.quizTitle}>WHICH IS THE MISSING LINE?</div>
<div className={styles.quizQuestionContainer}>
<pre class="prettyprint">function hello() &#123;
 const item = 
document.querySelector(".item");&#125;</pre>
</div>

<div className={styles.quizAnswers}>
  
  <div className={styles.answer}><div><span>A</span></div><pre class="prettyprint linenums">const item =document.querySelector(".item");</pre>
  </div>
  <div className={styles.answer}><div><span>B</span></div><pre class="prettyprint linenums">const item =document.querySelector(".item");</pre>
  </div>
</div>



        </div>
      </main>


    </div>
  )
}
